# See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
changelog:
  exclude:
    labels:
      - category-exclude
  categories:
    - title: New Features
      labels:
        - category-enhancement
        - enhancement # Legacy name
    - title: Bugfixes
      labels:
        - category-bugfix
    - title: '`public-api` library'
      labels:
        - category-public-api
    - title: '`rustdoc-json` library'
      labels:
        - category-rustdoc-json
    - title: '`rustup-toolchain` library'
      labels:
        - category-rustup-toolchain
    - title: Other Changes
      labels:
        - "*"
