# See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
changelog:
  exclude:
    labels:
      - category-exclude
  categories:
    - title: New Features
      labels:
        - category-enhancement
        - enhancement # Legacy name
    - title: Bugfixes
      labels:
        - category-bugfix
    - title: public_api library
      labels:
        - category-public_api
    - title: Other Changes
      labels:
        - "*"
