[package]
description = "List public items (public API) of Rust library crates. Enables diffing public API between releases and commits."
documentation = "https://docs.rs/public_items"
edition = "2021"
homepage = "https://github.com/Enselic/public_items"
license = "MIT"
name = "public_items"
repository = "https://github.com/Enselic/public_items"
version = "0.5.1"

[dependencies]
rustdoc-types = "0.7.0"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.77"
thiserror = "1.0.29"

[dev-dependencies]
pretty_assertions = "1.1.0"
