[package]
description = "List and diff public items (the public API) of Rust library crates. Relies on rustdoc JSON output from the nightly toolchain."
documentation = "https://docs.rs/public_items"
edition = "2021"
homepage = "https://github.com/Enselic/public_items"
license = "MIT"
name = "public_items"
repository = "https://github.com/Enselic/public_items"

# Also update https://github.com/Enselic/public_items#compatibility-matrix
version = "0.8.0"

[dependencies]
rustdoc-types = "0.10.0"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.77"
thiserror = "1.0.29"

[dev-dependencies]
assert_cmd = "2.0.4"
cargo_metadata = "0.14.2"
cargo_toml = "0.11.5"
pretty_assertions = "1.1.0"
serial_test = "0.6.0"

[workspace]
# Test-crates can't be part of the workspace because some test crates use
# different directories but the same name (e.g. `example_api`), which cargo does
# not allow.
exclude = [
    # Contains a public API that aim so to contain all public API item and
    # variants (with and without generics etc etc)
    "tests/crates/comprehensive_api",

    # Same as 'comprehensive_api', but for proc-macro stuff, because those needs
    # to be in a separate crate, see
    # https://stackoverflow.com/questions/56713877/why-do-proc-macros-have-to-be-defined-in-proc-macro-crate
    "tests/crates/comprehensive_api_proc_macro",

    # Contains different versions of the same small API. Used mainly to test
    # test the API-diffing functionality of this library.
    "tests/crates/example_api-v0.1.0",
    "tests/crates/example_api-v0.2.0",
]
