[package]
description = "List and diff public items (the public API) of Rust library crates. Relies on rustdoc JSON output from the nightly toolchain."
documentation = "https://docs.rs/public_items"
edition = "2021"
homepage = "https://github.com/Enselic/public_items"
license = "MIT"
name = "public_items"
repository = "https://github.com/Enselic/public_items"
version = "0.7.2"

[dependencies]
rustdoc-types = "0.10.0"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.77"
thiserror = "1.0.29"

[dev-dependencies]
assert_cmd = "2.0.4"
pretty_assertions = "1.1.0"

[workspace]
members = [
    "tests/crates/comprehensive_api",
]
