[package]
description = "List and diff public items (the public API) of Rust library crates. Relies on rustdoc JSON output from the nightly toolchain."
documentation = "https://docs.rs/public_items"
edition = "2021"
homepage = "https://github.com/Enselic/public_items"
license = "MIT"
name = "public_items"
repository = "https://github.com/Enselic/public_items"
version = "0.8.0" # Also update https://github.com/Enselic/public_items#compatibility-matrix

[dependencies]
rustdoc-types = "0.10.0"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.77"
thiserror = "1.0.29"

[dev-dependencies]
assert_cmd = "2.0.4"
pretty_assertions = "1.1.0"

[workspace]
members = [
    "tests/crates/comprehensive_api",
    "tests/crates/comprehensive_api_proc_macro", # proc-macro stuff needs to be in a separate crate, see https://stackoverflow.com/questions/56713877/why-do-proc-macros-have-to-be-defined-in-proc-macro-crate
]
