[package]
description = "List and diff public items (the public API) of Rust library crates. Requires nightly Rust to be installed."
documentation = "https://docs.rs/cargo-public-items"
edition = "2021"
homepage = "https://github.com/Enselic/cargo-public-items"
license = "MIT"
name = "cargo-public-items"
repository = "https://github.com/Enselic/cargo-public-items"
version = "0.6.0"

[dependencies]
anyhow = "1.0.53"
cargo_metadata = "0.14.2"
cargo_toml = "0.11.4"
clap = { version = "3.1.2", features = ["derive"] }

[dependencies.public_items]
# path = "/Users/martin/src/public_items"
version = "0.6.0"
