[package]
description = "List public items (public API) of library crates. Enables diffing public API between releases."
documentation = "https://docs.rs/cargo-public-items"
edition = "2021"
homepage = "https://github.com/Enselic/cargo-public-items"
license = "MIT"
name = "cargo-public-items"
repository = "https://github.com/Enselic/cargo-public-items"
version = "0.2.0"

[dependencies]
anyhow = "1.0.53"
cargo_toml = "0.10.3"

[dependencies.public_items]
# path = "/Users/martin/src/public_items"
version = "0.2.0"
