[package]
description = "This project has been renamed to `cargo-public-api`, see https://github.com/Enselic/cargo-public-api"
documentation = "https://github.com/Enselic/cargo-public-api/tree/cargo-public-items"
edition = "2021"
homepage = "https://github.com/Enselic/cargo-public-api/tree/cargo-public-items"
license = "MIT"
name = "cargo-public-items"
repository = "https://github.com/Enselic/cargo-public-api"
version = "0.8.0"
