[package]
description = "To test that we pass --cap-lints when building rustdoc JSON"
name = "lint_error"
version = "0.1.0"
edition = "2021"

[features]
missing-items = ["dep:example_api"]

[dependencies.example_api]
version = "0.2.0"
optional = true
