name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '33 3 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # The purpose of this job is to detect when a change to
  # https://github.com/rust-lang/rust/tree/master/src/rustdoc-json-types
  # requires that we release a new version of public_items to be compatible with
  # the latest nightly toolchain
  try-with-latest-rustdoc-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: trishume/syntect
        ref: v4.6.0
        path: syntect
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
    - run: RUSTDOCFLAGS='-Z unstable-options --output-format json' cargo +nightly doc --manifest-path ./syntect/Cargo.toml --lib --no-deps
    - run: cargo run ./syntect/target/doc/syntect.json
