# Allows you to easily see how release notes will look if you make a release
# now. Automatically updated.
name: Preview release notes

on:
  workflow_dispatch:
  # Since the release notes depend on labels (see .github/release.yml), rebuild
  # the release notes preview if labels change.
  pull_request:
    types: [labeled, unlabeled]
  # Since the release notes depend on what is on the main branch, rebuild the
  # release notes preview if main change.
  push:
    branches: [main]

jobs:
  show-release-notes:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    environment: preview-release-notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: cargo-public-api/cargo-public-api.github.io
          ssh-key: ${{ secrets.CARGO_PUBLIC_API_GITHUB_PAGES_DEPLOY_KEY }}
      - name: generate-notes
        run: |
          # Auto-generate release notes
          curl --request POST \
              --url ${{ github.api_url }}/repos/${{ github.repository }}/releases/generate-notes \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'content-type: application/json' \
              --data "{
                  \"tag_name\":\"main\",
                  \"target_commitish\":\"main\"
              }" > .response

          # Create header
          echo "## Preview of auto-generated release notes" > release-notes-preview.md

          # Create body
          cat .response | jq --raw-output .body | sed s/\\n/\n/g >> release-notes-preview.md

          # Make it easy to find what code to change to change the page
          echo -e "\n\n(This page was updated **$(date --iso-8601=seconds)** by \`${{ github.event_name }}\` via [Preview-release-notes.yml](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))" >> release-notes-preview.md
      - name: commit
        run: |
          git config user.name "EnselicCICD"
          git config user.email "junta-pixlar0l@icloud.com"
          git add release-notes-preview.md
          git commit -m "Update release-notes-preview.md"
      - name: push
        run: |
          git push origin main
