name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    uses: ./.github/workflows/CI.yml

  release:
    needs: verify
    environment: crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: ./scripts/release.sh
