name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    uses: .github/workflows/CI.yml

  release:
    needs: verify
    environment: cargo-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./scripts/release.sh
